name: Update Bing Wallpaper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update-wallpaper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4 # 升级到v4
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v4 # 升级到v4
        with:
          node-version: '18' # 建议升级到Node 18

      - name: Run bing.js
        run: bing.js # 检查实际脚本路径

      - name: Commit changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add images.json
          git commit -m "Updated Bing wallpaper for $(date +'%Y-%m-%d')"
          git remote set-url origin https://github.com/${{ github.repository }}
          git push origin HEAD:main # 确认分支名称
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # 隐式传递token
